"""Download a curated list of public printables; preserve original PDFs."""
import concurrent.futures, hashlib, json, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
items = []
def add(folder, name, url, source, ages, minutes, supplies, note):
    items.append(dict(file=f'{folder}/{name}.pdf', url=url, source=source,
                      ages=ages, minutes=minutes, supplies=supplies, note=note))
for solid, age, time in [('tetrahedron','7+',20),('cube','7+',20),('octahedron','8+',25),('dodecahedron','10+',45),('icosahedron','10+',45)]:
    add('02-Polyhedra-and-Folding',f'Mathigon-{solid}-net',f'https://static.mathigon.org/origami/{solid}-net.pdf',f'https://mathigon.org/origami/{solid}',age,time,'scissors, glue or tape, cardstock optional','Color before cutting; keep tabs; fold face edges and tabs. Single-sided.')
add('01-Coloring-and-Symmetry','Math-Equals-Love-15-Geometric-Coloring-Pages','https://mathequalslove.net/download/mathematical-tiling-coloring-pages-pdf/','https://mathequalslove.net/geometric-coloring-pages/','6+',15,'colored pencils','15 landscape coloring designs. Choose a page; ask which symmetries the coloring preserves.')
add('01-Coloring-and-Symmetry','Math-Equals-Love-Penrose-Tiling','https://mathequalslove.net/download/penrose-tiling-coloring-sheet-pdf/','https://mathequalslove.net/penrose-tiling-coloring-page/','7+',20,'colored pencils','Color a nonperiodic tiling patch; look for repeated local shapes.')
for folder,name,remote,slug,age,time,supplies,note in [
 ('01-Coloring-and-Symmetry','Map-Coloring','Map-Coloring-Activity-Guide','map-coloring','8+',25,'colored pencils or colored counters','Student instructions p. 6; maps pp. 7-14; answers p. 5. Sharing only a corner does not count as a border.'),
 ('01-Coloring-and-Symmetry','Color-Triangles','JRMF-Color-Triangles','color-triangles','7+',20,'three colors of pencils','Color patterns generated by a local rule; a bridge to cellular automata.'),
 ('02-Polyhedra-and-Folding','Hexaflexagons','Hexaflexagons-Festival-Guide','hexaflexagons','9+',35,'scissors, glue stick, pencils','Six-face flexagon. Instructions pp. 5-8; cutout template p. 9. Print single-sided; adult help useful.'),
 ('03-Paper-Games','Chomp','JRMF-Chomp','chomp','8+',20,'pencil; counters optional','Two-player chocolate-bar strategy game. Cross out eaten squares instead of using food.'),
 ('03-Paper-Games','Sprigs','Sprigs-Festival-Guide','sprigs','8+',20,'pencils or markers','Two-player drawing game. Instructions pp. 7-8; sheet p. 9. Sprigs differs from Sprouts; follow this guide.'),
 ('06-More-Math-Recreations','Pentominoes','Pentominoes-Activity-Guide','pentominoes','7+',30,'scissors, cardstock, pencil','Cut pieces from pp. 7-8 at the same print scale as the puzzle boards, pp. 9-16. Keep teacher answers separate.'),
 ('06-More-Math-Recreations','Doodles','Doodles-Activity-Guide','doodles','8+',20,'pencil; reusable sleeve optional','Trace each edge once. Instructions p. 6; puzzles pp. 7-12; answers p. 5.')]:
    add(folder,'JRMF-'+name,'https://jrmf.org/wp-content/uploads/'+remote+'.pdf','https://jrmf.org/puzzle/'+slug+'/',age,time,supplies,note)
add('03-Paper-Games','Maths-Week-Scotland-Dots-and-Boxes','https://mathsweek.scot/assets/files/Dots-Boxes-4x4-multi-grid.pdf','https://mathsweek.scot/assets/files/Dots-Boxes-4x4-multi-grid.pdf','6+',15,'two pencils','Two-player game with printable boards. Completing a box earns another turn.')
add('03-Paper-Games','Math-for-Love-Games-to-Play-at-Home','https://mathforlove.com/wp-content/uploads/2019/10/Math-Games-to-Play-at-Home.pdf','https://mathforlove.com/','7+',20,'pencils; some games use dice or counters','A broader game booklet; choose one game at a time.')
add('05-Orbifolds','Gould-Bringing-Orbifolds-out-of-the-Plane','https://archive.bridgesmathart.org/2020/bridges2020-507.pdf','https://archive.bridgesmathart.org/2020/bridges2020-507.html','12+ / leader',45,'ruler, colored pencils, scissors, tape; acrylic mirrors optional','Workshop explanation; use with the separate full-size handouts. Advanced, with adult facilitation.')
add('05-Orbifolds','Gould-Orbifold-Patterns-and-Matching-Cards','https://archive.bridgesmathart.org/2020/bridges2020_Supplement_82.pdf','https://archive.bridgesmathart.org/2020/bridges2020-507.html','10+ with leader',35,'color printer, scissors, tape','Full-size workshop supplement: wallpaper patterns and matching cards. Follow the companion paper.')
add('05-Orbifolds','Vi-Hart-Orbifold-and-Cut','https://archive.bridgesmathart.org/2013/bridges2013-635.pdf','https://archive.bridgesmathart.org/2013/bridges2013-635.html','leader / teens',45,'paper, scissors; other materials depend on extension','Leader reading about folding and cutting symmetry. Some extensions use craft knives; choose paper-and-scissors activities for children.')

def download(item):
    if 'mathscraftnz.org' in item['url']:
        return dict(item, status='external-only')
    path=ROOT/item['file'];path.parent.mkdir(parents=True,exist_ok=True)
    if not path.exists():
        p=subprocess.run(['curl','-fLsS','--retry','1','--max-time','50',item['url'],'-o',str(path)],capture_output=True,text=True)
        if p.returncode:
            path.unlink(missing_ok=True);return dict(item,status='failed',error=p.stderr)
    if not path.read_bytes().startswith(b'%PDF-'):
        path.rename(path.with_suffix('.download-error'));return dict(item,status='not PDF')
    return dict(item,status='downloaded',sha256=hashlib.sha256(path.read_bytes()).hexdigest(),bytes=path.stat().st_size,accessed='2026-10-01')

if __name__=='__main__':
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as pool:
        results=list(pool.map(download,items))
    (ROOT/'_sources'/'manifest.json').write_text(json.dumps(results,indent=2)+'\n')
    for r in results:print(r['status'],r['file'],r.get('error',''))
